/** Explicit input aliases, without the leading backslash. These insert characters;
 * only GHC's UnicodeSyntax spellings are interchangeable with Haskell syntax.
 */
const symbols: readonly (readonly string[])[] = [
  ['∷', '::', 'coloncolon'],
  ['→', '->', 'to', 'rightarrow'],
  ['←', '<-', 'leftarrow'],
  ['⇒', '=>', 'Rightarrow'],
  ['∀', 'forall'],
  ['★', '*', 'star'],
  ['⤚', '>-'],
  ['⤙', '-<'],
  ['⤜', '>>-'],
  ['⤛', '-<<'],
  ['⦇', '(|'],
  ['⦈', '|)'],
  ['⟦', '[|'],
  ['⟧', '|]'],
  ['⊸', '%1->', 'multimap'],
  ['α', 'alpha'],
  ['β', 'beta'],
  ['γ', 'gamma'],
  ['δ', 'delta'],
  ['ε', 'epsilon'],
  ['ζ', 'zeta'],
  ['η', 'eta'],
  ['θ', 'theta'],
  ['ι', 'iota'],
  ['κ', 'kappa'],
  ['λ', 'lambda'],
  ['μ', 'mu'],
  ['ν', 'nu'],
  ['ξ', 'xi'],
  ['ο', 'omicron'],
  ['π', 'pi'],
  ['ρ', 'rho'],
  ['σ', 'sigma'],
  ['τ', 'tau'],
  ['υ', 'upsilon'],
  ['φ', 'phi'],
  ['χ', 'chi'],
  ['ψ', 'psi'],
  ['ω', 'omega'],
  ['Α', 'Alpha'],
  ['Β', 'Beta'],
  ['Γ', 'Gamma'],
  ['Δ', 'Delta'],
  ['Ε', 'Epsilon'],
  ['Ζ', 'Zeta'],
  ['Η', 'Eta'],
  ['Θ', 'Theta'],
  ['Ι', 'Iota'],
  ['Κ', 'Kappa'],
  ['Λ', 'Lambda'],
  ['Μ', 'Mu'],
  ['Ν', 'Nu'],
  ['Ξ', 'Xi'],
  ['Ο', 'Omicron'],
  ['Π', 'Pi'],
  ['Ρ', 'Rho'],
  ['Σ', 'Sigma'],
  ['Τ', 'Tau'],
  ['Υ', 'Upsilon'],
  ['Φ', 'Phi'],
  ['Χ', 'Chi'],
  ['Ψ', 'Psi'],
  ['Ω', 'Omega'],
  ['ϵ', 'varepsilon'],
  ['ϑ', 'vartheta'],
  ['ϰ', 'varkappa'],
  ['ϕ', 'varphi'],
  ['ϱ', 'varrho'],
  ['ς', 'varsigma'],
  ['ϖ', 'varpi'],
  ['ℏ', 'hbar'],
  ['ℓ', 'ell'],
  ['∂', 'partial'],
  ['∇', 'nabla', 'grad'],
  ['∑', 'sum'],
  ['∏', 'prod'],
  ['∫', 'int'],
  ['∬', 'iint'],
  ['∭', 'iiint'],
  ['∮', 'oint'],
  ['√', 'sqrt'],
  ['∝', 'propto'],
  ['∼', 'sim'],
  ['≃', 'simeq'],
  ['≅', 'cong'],
  ['≪', 'll'],
  ['≫', 'gg'],
  ['⊗', 'otimes'],
  ['⊕', 'oplus'],
  ['⊙', 'odot'],
  ['†', 'dagger'],
  ['‡', 'ddagger'],
  ['°', 'degree'],
  ['ℵ', 'aleph'],
  ['⟨', 'langle'],
  ['⟩', 'rangle'],
  ['…', 'ldots'],
  ['⋯', 'cdots'],
  ['⋮', 'vdots'],
  ['⋱', 'ddots'],
  ['∃', 'exists'],
  ['∈', 'in', 'elem'],
  ['∉', 'notin'],
  ['⊆', 'subseteq'],
  ['⊂', 'subset'],
  ['∪', 'cup', 'union'],
  ['∩', 'cap', 'intersection'],
  ['∅', 'emptyset'],
  ['∞', 'infty'],
  ['≤', '<=', 'le', 'leq'],
  ['≥', '>=', 'ge', 'geq'],
  ['≠', '/=', 'ne', 'neq'],
  ['≡', '==', 'equiv'],
  ['≈', 'approx'],
  ['∧', '&&', 'land', 'wedge'],
  ['∨', '||', 'lor', 'vee'],
  ['¬', 'neg'],
  ['⊤', 'top'],
  ['⊥', 'bot', 'bottom'],
  ['∘', 'circ'],
  ['×', 'times'],
  ['⋅', 'cdot'],
  ['±', 'pm'],
  ['∓', 'mp'],
  ['↔', 'leftrightarrow'],
  ['⇔', 'Leftrightarrow', 'iff'],
  ['ℕ', 'Nat', 'mathbbN'],
  ['ℤ', 'Int', 'mathbbZ'],
  ['ℚ', 'Rat', 'mathbbQ'],
  ['ℝ', 'Real', 'mathbbR'],
  ['ℂ', 'Complex', 'mathbbC'],
  // Unicode supplies these subscript digits and letters. GHC accepts them
  // after the first character of an identifier, without UnicodeSyntax.
  ['₀', '_0'],
  ['₁', '_1'],
  ['₂', '_2'],
  ['₃', '_3'],
  ['₄', '_4'],
  ['₅', '_5'],
  ['₆', '_6'],
  ['₇', '_7'],
  ['₈', '_8'],
  ['₉', '_9'],
  ['ₐ', '_a'],
  ['ₑ', '_e'],
  ['ₕ', '_h'],
  ['ᵢ', '_i'],
  ['ⱼ', '_j'],
  ['ₖ', '_k'],
  ['ₗ', '_l'],
  ['ₘ', '_m'],
  ['ₙ', '_n'],
  ['ₒ', '_o'],
  ['ₚ', '_p'],
  ['ᵣ', '_r'],
  ['ₛ', '_s'],
  ['ₜ', '_t'],
  ['ᵤ', '_u'],
  ['ᵥ', '_v'],
  ['ₓ', '_x'],
  ['ᵦ', '_beta'],
  ['ᵧ', '_gamma'],
  ['ᵨ', '_rho'],
  ['ᵩ', '_phi'],
  ['ᵪ', '_chi'],
  // Lean-style superscript abbreviations. Signs are for mathematical text;
  // unlike the digits and letters, they cannot be part of Haskell identifiers.
  ['⁰', '^0'],
  ['¹', '^1'],
  ['²', '^2'],
  ['³', '^3'],
  ['⁴', '^4'],
  ['⁵', '^5'],
  ['⁶', '^6'],
  ['⁷', '^7'],
  ['⁸', '^8'],
  ['⁹', '^9'],
  ['⁺', '^+'],
  ['⁻', '^-'],
  ['⁻¹', '^-1'],
  ['ᵃ', '^a'],
  ['ᵇ', '^b'],
  ['ᶜ', '^c'],
  ['ᵈ', '^d'],
  ['ᵉ', '^e'],
  ['ᶠ', '^f'],
  ['ᵍ', '^g'],
  ['ʰ', '^h'],
  ['ⁱ', '^i'],
  ['ʲ', '^j'],
  ['ᵏ', '^k'],
  ['ˡ', '^l'],
  ['ᵐ', '^m'],
  ['ⁿ', '^n'],
  ['ᵒ', '^o'],
  ['ᵖ', '^p'],
  ['ʳ', '^r'],
  ['ˢ', '^s'],
  ['ᵗ', '^t'],
  ['ᵘ', '^u'],
  ['ᵛ', '^v'],
  ['ʷ', '^w'],
  ['ˣ', '^x'],
  ['ʸ', '^y'],
  ['ᶻ', '^z'],
  ['ᴬ', '^A'],
  ['ᴮ', '^B'],
  ['ᴰ', '^D'],
  ['ᴱ', '^E'],
  ['ᴳ', '^G'],
  ['ᴴ', '^H'],
  ['ᴵ', '^I'],
  ['ᴶ', '^J'],
  ['ᴷ', '^K'],
  ['ᴸ', '^L'],
  ['ᴹ', '^M'],
  ['ᴺ', '^N'],
  ['ᴼ', '^O'],
  ['ᴾ', '^P'],
  ['ᴿ', '^R'],
  ['ᵀ', '^T'],
  ['ᵁ', '^U'],
  ['ⱽ', '^V'],
  ['ᵂ', '^W'],
];

export const unicodeSymbols: ReadonlyMap<string, string> = new Map(
  symbols.flatMap(([symbol, ...aliases]) => aliases.map((alias) => [alias, symbol] as const)),
);
